name: '🕵️'

on:
  push:
    branches:
      - '**'

jobs:
  check:
    runs-on: codeberg-small
    steps:

      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache: true

      - run: go test -v -vet 'all' ./...
